//! One device, as a state machine.
//!
//! Bytes go in, events come out, and commands go back. Nothing here
//! performs input or output, so the same code runs behind a desktop
//! Bluetooth stack, a browser's, or a test with no Bluetooth at all.

use intomind_protocol as p;
use intomind_protocol::control::{Opcode, Request, Status};
use intomind_protocol::device_info::{capability, DeviceInfo, capability_high};
use intomind_protocol::pipeline::{self as pipe, Chain, PredictionInput};
use intomind_protocol::frame::{self, Continuity, DataHeader};
use intomind_protocol::status::StatusMsg;
use intomind_protocol::{uuid_fill, Error as WireError};

use crate::timebase::{Exchange, Timebase};
use crate::Error;

/// Bytes to write, and where to write them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Command {
    /// The sixteen bit fill of the characteristic. `protocol::uuid128`
    /// turns it into the full identifier your stack wants.
    pub characteristic: u16,
    pub bytes: Vec<u8>,
    /// Whether the write must be acknowledged.
    pub with_response: bool,
}

/// A run of samples that arrived together.
#[derive(Debug, Clone, PartialEq)]
pub struct Batch {
    /// The device's own index for the first sample.
    pub index: u32,
    /// The device time of the first sample, in the device's ticks.
    pub device_time: u64,
    pub channels: usize,
    /// Converter counts, one row per sample.
    pub counts: Vec<i32>,
    /// Lead-off status latched with the last sample.
    pub leadoff: u8,
    pub gain: u8,
    pub sample_rate_hz: u16,
    /// The mode the samples were taken in: 0 normal, 1 test signal, 2 inputs
    /// shorted, 3 synthetic (1.3).
    pub mode: u8,
    /// 1.3: the samples were generated by the device, not measured: the
    /// packet was type 0x04. Never store one as a measurement.
    pub synthetic: bool,
}

impl Batch {
    pub fn rows(&self) -> usize {
        self.counts.len() / self.channels
    }

    /// One sample, in microvolts, with the device's own reference and
    /// width. Nothing is assumed about either.
    pub fn microvolts(&self, row: usize, channel: usize, info: &DeviceInfo) -> f64 {
        let count = self.counts[row * self.channels + channel];
        count as f64 * (2.0 * info.vref_uv as f64) / (self.gain as f64 * (1u64 << info.adc_bits) as f64)
    }
}

/// A break in the timeline, written down rather than smoothed over.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Gap {
    pub last_index_before: u32,
    pub first_index_after: u32,
    /// Samples missing. None for a re-base, whose extent is not a number.
    pub samples_lost: Option<u32>,
    pub device_time_before: u64,
    pub device_time_after: u64,
}

impl Gap {
    pub fn is_rebase(&self) -> bool {
        self.samples_lost.is_none()
    }
}

/// What arrived.
#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    Samples(Batch),
    /// Announced before the batch that follows it.
    Gap(Gap),
    Status(StatusMsg),
    /// A control answer. A caller that issued a command matches on this.
    Answer { opcode: u8, status: Status, payload: Vec<u8> },
    Prediction(Prediction),
    /// 1.2: one notification of the encoder's output, a whole vector or a
    /// part of one. `embeddings::Assembler` puts them into whole windows.
    Embedding(crate::embeddings::Embedding),
    /// A notification that was not a message. Counted, never guessed at.
    Undecodable,
    /// A data packet this session already passed on, delivered again by
    /// the host's Bluetooth stack: dropped, never passed on twice, and
    /// counted. It means another program on the same computer is listening
    /// to the device, since the system sends each notification once per
    /// subscriber and every subscriber hears all of the copies. `index` is
    /// the repeated packet's first sample.
    Duplicate {
        /// The first sample index of the packet that arrived again.
        index: u32,
    },
}

/// One window's model output.
#[derive(Debug, Clone, PartialEq)]
pub struct Prediction {
    pub head_slot: u8,
    pub head_id: [u8; 8],
    pub index: u32,
    pub device_time: u64,
    pub window_samples: u16,
    pub gap_in_window: bool,
    pub duty_reduced: bool,
    pub leadoff_in_window: bool,
    pub outputs: Vec<f32>,
}

/// One device.
#[derive(Debug, Default)]
pub struct Session {
    info: Option<DeviceInfo>,
    timebase: Option<Timebase>,
    previous: Option<(u32, u8, u64)>,
    /// Samples the device says never arrived, over this session.
    pub samples_lost: u32,
    pub rebases: u32,
    pub undecodable: u32,
    /// Data packets delivered twice by the host and dropped: see
    /// `Event::Duplicate`.
    pub duplicates: u32,
    /// The first index and device time of the last few packets passed on,
    /// what a copy is recognized by.
    recent: [Option<(u32, u64)>; 8],
    recent_at: usize,
}

impl Session {
    pub fn new() -> Session {
        Session::default()
    }

    /// What was read from the device info characteristic.
    pub fn on_device_info(&mut self, bytes: &[u8]) -> Result<DeviceInfo, Error> {
        let info = DeviceInfo::parse(bytes)?;
        self.timebase = Some(Timebase::new(info.time_tick_hz));
        self.info = Some(info);
        Ok(info)
    }

    pub fn info(&self) -> Result<&DeviceInfo, Error> {
        self.info.as_ref().ok_or(Error::NoDeviceInfo)
    }

    /// Whether the device claims a capability.
    pub fn can(&self, capability: u16) -> bool {
        self.info.map(|i| i.capabilities & capability != 0).unwrap_or(false)
    }

    pub fn timebase(&self) -> Option<&Timebase> {
        self.timebase.as_ref()
    }

    /// Host time for a device time, once enough exchanges have been taken.
    pub fn host_time(&self, device_ticks: u64) -> Option<f64> {
        self.timebase.as_ref()?.host_time(device_ticks)
    }

    fn command(&self, opcode: Opcode, arg: Option<u8>) -> Command {
        let mut bytes = [0u8; 2];
        let n = Request { opcode, arg }.encode(&mut bytes).unwrap_or(0);
        Command { characteristic: uuid_fill::CONTROL, bytes: bytes[..n].to_vec(), with_response: true }
    }

    /// Ask the device to stream.
    pub fn start_stream(&self) -> Command {
        self.command(Opcode::StartStream, None)
    }

    pub fn stop_stream(&self) -> Command {
        self.command(Opcode::StopStream, None)
    }

    /// Set the rate, in samples per second. The device refuses a change
    /// while it is streaming, so every sample of a recording sits under
    /// one configuration.
    pub fn set_rate(&self, sps: u16) -> Result<Command, Error> {
        let code = match sps {
            1000 => 4,
            500 => 5,
            250 => 6,
            _ => return Err(Error::Wire(WireError::Invalid)),
        };
        Ok(self.command(Opcode::SetRate, Some(code)))
    }

    pub fn set_gain(&self, gain: u8) -> Result<Command, Error> {
        let code = frame::GAIN_BY_CODE.iter().position(|&g| g == gain).ok_or(Error::Wire(WireError::Invalid))?;
        Ok(self.command(Opcode::SetGain, Some(code as u8)))
    }

    /// 0 for the electrodes, 1 for the internal test signal, 2 for
    /// shorted inputs.
    pub fn set_mode(&self, mode: u8) -> Result<Command, Error> {
        if mode > p::control::mode::SYNTHETIC {
            return Err(Error::Wire(WireError::Invalid));
        }
        if mode == p::control::mode::SYNTHETIC {
            // 1.3: the device generates the signal with its converter off.
            // Only a device that claims it; at 500 samples a second, and
            // never while streaming, which the device refuses for itself.
            self.require_high(capability_high::SYNTHETIC, "synthetic")?;
        }
        Ok(self.command(Opcode::SetMode, Some(mode)))
    }

    pub fn set_leadoff(&self, on: bool) -> Result<Command, Error> {
        if !self.can(p::device_info::capability::LEADOFF) {
            return Err(Error::NotCapable("leadoff"));
        }
        Ok(self.command(Opcode::SetLeadoff, Some(on as u8)))
    }

    /// Ask the device what time it is. Note the host clock either side and
    /// give both to `on_time_sync`.
    pub fn time_sync(&self) -> Command {
        self.command(Opcode::TimeSync, None)
    }

    /// The answer to a time request, with the host clock either side of it.
    pub fn on_time_sync(&mut self, payload: &[u8], before: f64, after: f64) -> Result<(), Error> {
        if payload.len() < 8 {
            return Err(Error::Wire(WireError::Truncated));
        }
        let ticks = u64::from_le_bytes(payload[..8].try_into().unwrap());
        let tb = self.timebase.as_mut().ok_or(Error::NoDeviceInfo)?;
        tb.observe(Exchange { before, after, device_ticks: ticks });
        Ok(())
    }

    pub fn reset_epoch(&mut self) -> Command {
        self.previous = None;
        self.command(Opcode::ResetEpoch, None)
    }

    pub fn set_predictions(&self, on: bool) -> Result<Command, Error> {
        if !self.can(p::device_info::capability::MODEL) {
            return Err(Error::NotCapable("model"));
        }
        Ok(self.command(Opcode::SetPredictions, Some(on as u8)))
    }

    pub fn select_head(&self, slot: u8) -> Result<Command, Error> {
        if !self.can(p::device_info::capability::HEADS) {
            return Err(Error::NotCapable("heads"));
        }
        Ok(self.command(Opcode::SelectHead, Some(slot)))
    }

    /// Ask what is in every head slot. The answer arrives as an
    /// `Event::Answer`, and `protocol::control::ListHeads` reads it.
    pub fn list_heads(&self) -> Result<Command, Error> {
        if !self.can(p::device_info::capability::HEADS) {
            return Err(Error::NotCapable("heads"));
        }
        Ok(self.command(Opcode::ListHeads, None))
    }

    /// Erase a head slot. Slot zero is the device's own and cannot be
    /// erased, which the device enforces.
    pub fn remove_head(&self, slot: u8) -> Result<Command, Error> {
        if !self.can(p::device_info::capability::HEADS) {
            return Err(Error::NotCapable("heads"));
        }
        Ok(self.command(Opcode::RemoveHead, Some(slot)))
    }

    fn require(&self, cap: u16, name: &'static str) -> Result<(), Error> {
        if self.can(cap) { Ok(()) } else { Err(Error::NotCapable(name)) }
    }

    /// Whether the device claims a capability from the second word of
    /// Device Info, bits 16 and up, a `protocol::device_info::capability_high`
    /// value. A device whose Device Info ends at 76 bytes claims none.
    pub fn can_high(&self, capability: u32) -> bool {
        self.info.map(|i| i.capabilities_high & capability != 0).unwrap_or(false)
    }

    fn require_high(&self, cap: u32, name: &'static str) -> Result<(), Error> {
        if self.can_high(cap) { Ok(()) } else { Err(Error::NotCapable(name)) }
    }

    /// A request that carries a payload after its opcode.
    fn command_with(&self, opcode: Opcode, payload: &[u8]) -> Command {
        let mut bytes = vec![0u8; 1 + payload.len()];
        let n = p::control::encode_request_with_payload(opcode, payload, &mut bytes).unwrap_or(0);
        bytes.truncate(n);
        Command { characteristic: uuid_fill::CONTROL, bytes, with_response: true }
    }

    // --- processing, on devices that run a chain ------------------------------
    //
    // The device preprocesses its own signal. When a chain is in force only
    // its output streams, and the chain is readable at any time, so a
    // recording can say exactly what produced its samples. The rules a chain
    // must meet are the device's, in the `intomind-pipeline` crate, so a
    // chain that cannot run is refused here with its reason before anything
    // is sent. The device refuses a change while streaming: stop, set, start.

    /// Ask for the stage kinds the device runs. The answer arrives as an
    /// `Event::Answer`, and `protocol::pipeline::Catalog` reads it.
    pub fn pipeline_catalog(&self) -> Result<Command, Error> {
        self.require(capability::PIPELINE, "pipeline")?;
        Ok(self.command(Opcode::GetPipelineCatalog, None))
    }

    /// Ask for the chain in force and whether it is the device's own default
    /// for its current rate or one a host set.
    /// `protocol::pipeline::PipelineState` reads the answer.
    pub fn pipeline(&self) -> Result<Command, Error> {
        self.require(capability::PIPELINE, "pipeline")?;
        Ok(self.command(Opcode::GetPipeline, None))
    }

    /// Put a chain on the device's signal path, checked here first against
    /// the rate the device runs at.
    pub fn set_pipeline(&self, chain: &Chain, rate_sps: u32) -> Result<Command, Error> {
        self.require(capability::PIPELINE, "pipeline")?;
        intomind_pipeline::check(chain, rate_sps).map_err(Error::Chain)?;
        let mut body = [0u8; pipe::MAX_ENCODED_LEN];
        let n = chain.encode(&mut body)?;
        Ok(self.command_with(Opcode::SetPipeline, &body[..n]))
    }

    /// The natural signal, as this host's choice.
    pub fn clear_pipeline(&self) -> Result<Command, Error> {
        self.require(capability::PIPELINE, "pipeline")?;
        Ok(self.command(Opcode::ClearPipeline, None))
    }

    /// The device's own default chain for its current rate.
    pub fn restore_pipeline_default(&self) -> Result<Command, Error> {
        self.require(capability::PIPELINE, "pipeline")?;
        Ok(self.command(Opcode::RestorePipelineDefault, None))
    }

    /// Ask where the model's input comes from, with the chain in effect.
    /// `protocol::pipeline::PredictionInput` reads the answer.
    pub fn prediction_input(&self) -> Result<Command, Error> {
        self.require(capability::MODEL, "model")?;
        Ok(self.command(Opcode::GetPredictionInput, None))
    }

    /// Point the model at the stream as it is, at the natural signal, or at
    /// a chain of its own, without touching the stream. Only the model's own
    /// source carries a chain, checked here against the rate.
    pub fn set_prediction_input(&self, input: &PredictionInput, rate_sps: u32) -> Result<Command, Error> {
        self.require(capability::MODEL, "model")?;
        if input.source == pipe::input_source::OWN_CHAIN {
            intomind_pipeline::check(&input.chain, rate_sps).map_err(Error::Chain)?;
        } else if !input.chain.is_natural() {
            return Err(Error::Wire(WireError::Invalid));
        }
        let mut body = [0u8; 1 + pipe::MAX_ENCODED_LEN];
        let n = input.encode(&mut body)?;
        Ok(self.command_with(Opcode::SetPredictionInput, &body[..n]))
    }

    /// The bias drive: `bias_mode::OFF`, `ON`, or `LOOP_OPEN`, on a device
    /// that claims one.
    pub fn set_bias(&self, mode: u8) -> Result<Command, Error> {
        self.require(capability::BIAS_DRIVE, "bias_drive")?;
        if mode > pipe::bias_mode::LOOP_OPEN {
            return Err(Error::Wire(WireError::Invalid));
        }
        Ok(self.command(Opcode::SetBias, Some(mode)))
    }

    /// Ask for the bias output measured. `protocol::pipeline::BiasDiagnostic`
    /// reads the answer.
    pub fn bias_diagnostic(&self) -> Result<Command, Error> {
        self.require(capability::BIAS_DRIVE, "bias_drive")?;
        Ok(self.command(Opcode::GetBiasDiagnostic, None))
    }

    // --- the lamp, the converter's registers, embeddings (1.2) ---------------

    /// Ask for the status lamp's level. The answer's one byte is a
    /// `protocol::control::indicator` value.
    pub fn indicator(&self) -> Result<Command, Error> {
        self.require(capability::INDICATOR, "indicator")?;
        Ok(self.command(Opcode::GetIndicator, None))
    }

    /// Put the lamp at a level, a `protocol::control::indicator` value: silent,
    /// reserved (the default: low battery and a converter fault), or verbose.
    /// The device keeps it across power cycles.
    pub fn set_indicator(&self, level: u8) -> Result<Command, Error> {
        self.require(capability::INDICATOR, "indicator")?;
        if level > p::control::indicator::VERBOSE {
            return Err(Error::Wire(WireError::Invalid));
        }
        Ok(self.command(Opcode::SetIndicator, Some(level)))
    }

    /// Blink the lamp so this device can be told from others, for 1 to 30
    /// seconds at every level; 0 stops one in progress.
    pub fn identify(&self, seconds: u8) -> Result<Command, Error> {
        self.require(capability::INDICATOR, "indicator")?;
        if seconds > p::control::indicator::IDENTIFY_MAX_SECONDS {
            return Err(Error::Wire(WireError::Invalid));
        }
        Ok(self.command(Opcode::Identify, Some(seconds)))
    }

    /// Ask for the converter's registers, raw, for debugging. Read only, and
    /// only while not streaming. `protocol::control::ConverterRegisters`
    /// reads the answer.
    pub fn converter_registers(&self) -> Result<Command, Error> {
        self.require(capability::CONVERTER_REGISTERS, "converter_registers")?;
        Ok(self.command(Opcode::GetConverterRegisters, None))
    }

    /// Ask the device for its encoder's output for each window while it
    /// streams, in a form, or turn it off with `None`. Whole windows come
    /// from `embeddings::Assembler` fed with `Event::Embedding`.
    pub fn set_embeddings(&self, form: Option<crate::embeddings::Form>) -> Result<Command, Error> {
        self.require(capability::EMBEDDINGS, "embeddings")?;
        let code = form.map_or(p::embeddings::form::OFF, |f| f.code());
        Ok(self.command(Opcode::SetEmbeddings, Some(code)))
    }

    // ---- 1.3: the model's cadence and the device's name -------------------

    /// Ask how often the model describes a window, and the least interval the
    /// device keeps. `protocol::control::interval::ModelInterval` reads the
    /// answer: the interval in force, then the minimum, both in seconds.
    pub fn model_interval(&self) -> Result<Command, Error> {
        self.require(capability::MODEL_CADENCE, "model_cadence")?;
        Ok(self.command(Opcode::GetModelInterval, None))
    }

    /// Set how often the model describes a window, in seconds. Zero is every
    /// window the device can, each the newest complete one; `T` places the
    /// windows on a grid of `T` seconds. The device refuses a value below
    /// its minimum, and keeps the setting across power cycles.
    pub fn set_model_interval(&self, seconds: u16) -> Result<Command, Error> {
        self.require(capability::MODEL_CADENCE, "model_cadence")?;
        Ok(self.command_with(Opcode::SetModelInterval, &seconds.to_le_bytes()))
    }

    /// Ask for the name and the adjective a host set, each possibly empty.
    /// `protocol::control::name::parse_parts` reads the answer.
    pub fn name(&self) -> Result<Command, Error> {
        self.require_high(capability_high::DEVICE_NAME, "device_name")?;
        Ok(self.command(Opcode::GetName, None))
    }

    /// Name the device. It composes `name's adjective product`, dropping the
    /// possessive without a name and the adjective when empty, and that
    /// composition must fit the 29 bytes a scan response carries, so every
    /// scan list shows the whole of it. `product` is the device's product
    /// name, which its advertised name ends with. Refused here when a part
    /// has a leading or trailing space or a control character, or when the
    /// composition would not fit; the device keeps both parts across power
    /// cycles and advertises the new name at once.
    pub fn set_name(&self, name: &str, adjective: &str, product: &str) -> Result<Command, Error> {
        use p::control::name as parts;
        self.require_high(capability_high::DEVICE_NAME, "device_name")?;
        let (n, a) = (name.as_bytes(), adjective.as_bytes());
        if !parts::valid_part(n) || !parts::valid_part(a) || !parts::acceptable(n, a, product.as_bytes()) {
            return Err(Error::Wire(WireError::Invalid));
        }
        let mut payload = [0u8; 2 + 2 * parts::MAX_COMPOSED];
        let len = parts::encode_parts(n, a, &mut payload).map_err(Error::Wire)?;
        Ok(self.command_with(Opcode::SetName, &payload[..len]))
    }

    /// Hand in one notification, and take whatever it meant.
    ///
    /// A batch that follows a break is preceded by the gap, so a caller
    /// that writes samples down writes the gap down first and can never
    /// splice.
    pub fn on_notification(&mut self, characteristic: u16, bytes: &[u8]) -> Vec<Event> {
        match characteristic {
            uuid_fill::EEG_DATA => self.on_samples(bytes),
            uuid_fill::STATUS => match StatusMsg::parse(bytes) {
                Ok(s) => vec![Event::Status(s)],
                Err(_) => self.undecodable(),
            },
            uuid_fill::CONTROL_RSP => match p::control::Response::parse(bytes) {
                Ok(r) => vec![Event::Answer { opcode: r.opcode as u8, status: r.status, payload: r.payload.to_vec() }],
                Err(_) => self.undecodable(),
            },
            uuid_fill::EMBEDDINGS => match crate::embeddings::Embedding::parse(bytes) {
                Ok(e) => vec![Event::Embedding(e)],
                Err(_) => self.undecodable(),
            },
            uuid_fill::PREDICTIONS => match p::predictions::PredictionHeader::parse(bytes) {
                Ok((h, outputs)) => vec![Event::Prediction(Prediction {
                    head_slot: h.head_slot,
                    head_id: h.head_id,
                    index: h.sample_index,
                    device_time: h.device_time,
                    window_samples: h.window_samples,
                    gap_in_window: h.flags & p::predictions::flags::GAP_IN_WINDOW != 0,
                    duty_reduced: h.flags & p::predictions::flags::DUTY_REDUCED != 0,
                    leadoff_in_window: h.flags & p::predictions::flags::LEADOFF_IN_WINDOW != 0,
                    outputs: outputs.iter().collect(),
                })],
                Err(_) => self.undecodable(),
            },
            _ => self.undecodable(),
        }
    }

    fn undecodable(&mut self) -> Vec<Event> {
        self.undecodable += 1;
        vec![Event::Undecodable]
    }

    fn on_samples(&mut self, bytes: &[u8]) -> Vec<Event> {
        let Some(info) = self.info else {
            return self.undecodable();
        };
        let channels = info.channel_count as usize;
        let (h, payload) = match DataHeader::parse(bytes, channels) {
            Ok(x) => x,
            Err(_) => return self.undecodable(),
        };
        let mut events = Vec::with_capacity(2);
        if let Some((prev_index, prev_n, prev_time)) = self.previous {
            // A packet with the first index and the device time of one just
            // passed on is that packet again, delivered twice by the host.
            // Dropped and counted, so no sample is passed on twice and no
            // break is announced that did not happen. A device that restarts
            // its count carries a new device time, so a restart is never
            // mistaken for a copy, and anything else is judged by the
            // contract's continuity rule unchanged.
            let key = (h.sample_index, h.device_time);
            if self.recent.contains(&Some(key)) {
                self.duplicates = self.duplicates.saturating_add(1);
                return vec![Event::Duplicate { index: h.sample_index }];
            }
            match frame::continuity(prev_index, prev_n, h.sample_index, h.flags) {
                Continuity::Continuous => {}
                Continuity::Gap { lost } => {
                    self.samples_lost = self.samples_lost.saturating_add(lost);
                    events.push(Event::Gap(Gap {
                        last_index_before: prev_index.wrapping_add(prev_n as u32).wrapping_sub(1),
                        first_index_after: h.sample_index,
                        samples_lost: Some(lost),
                        device_time_before: prev_time,
                        device_time_after: h.device_time,
                    }));
                }
                Continuity::Break => {
                    self.rebases = self.rebases.saturating_add(1);
                    events.push(Event::Gap(Gap {
                        last_index_before: prev_index.wrapping_add(prev_n as u32).wrapping_sub(1),
                        first_index_after: h.sample_index,
                        samples_lost: None,
                        device_time_before: prev_time,
                        device_time_after: h.device_time,
                    }));
                }
            }
        }
        self.previous = Some((h.sample_index, h.n_samples, h.device_time));
        self.recent[self.recent_at] = Some((h.sample_index, h.device_time));
        self.recent_at = (self.recent_at + 1) % self.recent.len();
        let mut counts = Vec::with_capacity(h.n_samples as usize * channels);
        for i in 0..h.n_samples as usize {
            for c in 0..channels {
                let o = (i * channels + c) * 3;
                counts.push(frame::int24_be([payload[o], payload[o + 1], payload[o + 2]]));
            }
        }
        events.push(Event::Samples(Batch {
            index: h.sample_index,
            device_time: h.device_time,
            channels,
            counts,
            leadoff: h.loff_statp,
            gain: frame::GAIN_BY_CODE[h.gain_code as usize],
            sample_rate_hz: frame::sps_of_rate_code(h.rate_code).unwrap_or(0),
            mode: (h.flags & frame::flags::MODE_MASK) >> frame::flags::MODE_SHIFT,
            synthetic: bytes[0] == frame::PACKET_TYPE_SYNTHETIC,
        }));
        events
    }
}
